m# Change these first
owner: m-team-kit # Your GitHub organization or username, where this repository lives
repo: templates-status # The name of this repository

sites:
  # cookiecutter-web Frontend
  - name: AI repository template generator (WebApp)
    url: https://templates.cloud.ai4eosc.eu/
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
  # cookiecutter-web API
  - name: AI repository template generator (API)
    url: https://templates.cloud.ai4eosc.eu/api/v1/
    icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
assignees: # Users to assign downtime issues (optional)
  - vykozlov
  - BorjaEst
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #c.n.a.m.e.: demo.upptime.js.org
  baseUrl: /templates-status
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status monitoring for the AI repository template service
  introTitle: "Status monitoring for the AI repository template service"
  introMessage: This is a status page which uses **real-time** data from our [AI repository template service](https://templates.cloud.ai4eosc.eu)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
